openapi: 3.0.3
info:
  title: 'Cardano Mercury: Invoice'
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8100'
paths:
  /api/v1/customers:
    get:
      summary: 'List Customers'
      operationId: listCustomers
      description: ''
      parameters:
        -
          in: query
          name: search
          description: 'Search for customers by name or tax number'
          example: 'John Doe'
          required: false
          schema:
            type: string
            description: 'Search for customers by name or tax number'
            example: 'John Doe'
        -
          in: query
          name: per_page
          description: 'Number of results per page (Min 25, Max 100)'
          example: 25
          required: false
          schema:
            type: integer
            description: 'Number of results per page (Min 25, Max 100)'
            example: 25
        -
          in: query
          name: page
          description: 'Page number'
          example: 1
          required: false
          schema:
            type: integer
            description: 'Page number'
            example: 1
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      customer_id: 1
                      name: 'Roman Streich'
                      tax_number: 01JAC01XKMHKR17KKTGDCQ6HNJ
                      tax_rate: 17.5
                      created_at: '2024-10-17 01:04:12'
                      updated_at: '2024-10-17 01:04:12'
                    -
                      customer_id: 1
                      name: 'Dr. Katelynn Cormier II'
                      tax_number: 01JAC01XKNB2ED8NWZ7PBDDYQD
                      tax_rate: 17.5
                      created_at: '2024-10-17 01:04:12'
                      updated_at: '2024-10-17 01:04:12'
                  links:
                    first: '/?page=1'
                    last: null
                    prev: null
                    next: null
                  meta:
                    current_page: 1
                    from: 1
                    path: /
                    per_page: 25
                    to: 2
                properties:
                  data:
                    type: array
                    example:
                      -
                        customer_id: 1
                        name: 'Roman Streich'
                        tax_number: 01JAC01XKMHKR17KKTGDCQ6HNJ
                        tax_rate: 17.5
                        created_at: '2024-10-17 01:04:12'
                        updated_at: '2024-10-17 01:04:12'
                      -
                        customer_id: 1
                        name: 'Dr. Katelynn Cormier II'
                        tax_number: 01JAC01XKNB2ED8NWZ7PBDDYQD
                        tax_rate: 17.5
                        created_at: '2024-10-17 01:04:12'
                        updated_at: '2024-10-17 01:04:12'
                    items:
                      type: object
                      properties:
                        customer_id:
                          type: integer
                          example: 1
                        name:
                          type: string
                          example: 'Roman Streich'
                        tax_number:
                          type: string
                          example: 01JAC01XKMHKR17KKTGDCQ6HNJ
                        tax_rate:
                          type: number
                          example: 17.5
                        created_at:
                          type: string
                          example: '2024-10-17 01:04:12'
                        updated_at:
                          type: string
                          example: '2024-10-17 01:04:12'
                  links:
                    type: object
                    properties:
                      first:
                        type: string
                        example: '/?page=1'
                      last:
                        type: string
                        example: null
                      prev:
                        type: string
                        example: null
                      next:
                        type: string
                        example: null
                  meta:
                    type: object
                    properties:
                      current_page:
                        type: integer
                        example: 1
                      from:
                        type: integer
                        example: 1
                      path:
                        type: string
                        example: /
                      per_page:
                        type: integer
                        example: 25
                      to:
                        type: integer
                        example: 2
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthorized
                properties:
                  message:
                    type: string
                    example: Unauthorized
        404:
          description: ''
          content:
            application/json:
              schema:
                oneOf:
                  -
                    description: 'Not Found'
                    type: object
                    example:
                      message: 'Route or Record Not found'
                    properties:
                      message:
                        type: string
                        example: 'Route or Record Not found'
                  -
                    description: 'Bad Request'
                    type: object
                    example:
                      message: 'The POST method is not supported for route api/v1/customers/1/phones/16. Supported methods: GET, HEAD, PUT, PATCH'
                    properties:
                      message:
                        type: string
                        example: 'The POST method is not supported for route api/v1/customers/1/phones/16. Supported methods: GET, HEAD, PUT, PATCH'
        500:
          description: 'Internal Server Error'
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Internal Server Error'
                properties:
                  message:
                    type: string
                    example: 'Internal Server Error'
      tags:
        - Customers
    post:
      summary: 'Create Customer'
      operationId: createCustomer
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    customer_id: 1
                    name: 'Mireya Windler'
                    tax_number: 01JAC01XKYF12H6RZ4607C8GQ4
                    tax_rate: 17.5
                    created_at: '2024-10-17 01:04:12'
                    updated_at: '2024-10-17 01:04:12'
                properties:
                  data:
                    type: object
                    properties:
                      customer_id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: 'Mireya Windler'
                      tax_number:
                        type: string
                        example: 01JAC01XKYF12H6RZ4607C8GQ4
                      tax_rate:
                        type: number
                        example: 17.5
                      created_at:
                        type: string
                        example: '2024-10-17 01:04:12'
                      updated_at:
                        type: string
                        example: '2024-10-17 01:04:12'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthorized
                properties:
                  message:
                    type: string
                    example: Unauthorized
        404:
          description: ''
          content:
            application/json:
              schema:
                oneOf:
                  -
                    description: 'Not Found'
                    type: object
                    example:
                      message: 'Route or Record Not found'
                    properties:
                      message:
                        type: string
                        example: 'Route or Record Not found'
                  -
                    description: 'Bad Request'
                    type: object
                    example:
                      message: 'The POST method is not supported for route api/v1/customers/1/phones/16. Supported methods: GET, HEAD, PUT, PATCH'
                    properties:
                      message:
                        type: string
                        example: 'The POST method is not supported for route api/v1/customers/1/phones/16. Supported methods: GET, HEAD, PUT, PATCH'
        422:
          description: 'Validation Failed'
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Validation Failed'
                  fields:
                    type:
                      - 'The selected type is invalid.'
                    name:
                      - 'The name field must not be greater than 64 characters.'
                properties:
                  message:
                    type: string
                    example: 'Validation Failed'
                  fields:
                    type: object
                    properties:
                      type:
                        type: array
                        example:
                          - 'The selected type is invalid.'
                        items:
                          type: string
                      name:
                        type: array
                        example:
                          - 'The name field must not be greater than 64 characters.'
                        items:
                          type: string
        500:
          description: 'Internal Server Error'
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Internal Server Error'
                properties:
                  message:
                    type: string
                    example: 'Internal Server Error'
      tags:
        - Customers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must be at least 3 characters. Must not be greater than 64 characters.'
                  example: 'John Doe'
                tax_number:
                  type: string
                  description: 'Must be at least 3 characters. Must not be greater than 64 characters.'
                  example: ABCD-1234
                tax_rate:
                  type: number
                  description: 'Must be between 0 and 100.'
                  example: 12.5
              required:
                - name
  '/api/v1/customers/{id}':
    get:
      summary: 'Get Customer'
      operationId: getCustomer
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    customer_id: 1
                    name: 'Rachelle Schowalter PhD'
                    tax_number: 01JAC01XM4F8DFPAK2D8EZQRKG
                    tax_rate: 17.5
                    created_at: '2024-10-17 01:04:12'
                    updated_at: '2024-10-17 01:04:12'
                properties:
                  data:
                    type: object
                    properties:
                      customer_id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: 'Rachelle Schowalter PhD'
                      tax_number:
                        type: string
                        example: 01JAC01XM4F8DFPAK2D8EZQRKG
                      tax_rate:
                        type: number
                        example: 17.5
                      created_at:
                        type: string
                        example: '2024-10-17 01:04:12'
                      updated_at:
                        type: string
                        example: '2024-10-17 01:04:12'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthorized
                properties:
                  message:
                    type: string
                    example: Unauthorized
        404:
          description: ''
          content:
            application/json:
              schema:
                oneOf:
                  -
                    description: 'Not Found'
                    type: object
                    example:
                      message: 'Route or Record Not found'
                    properties:
                      message:
                        type: string
                        example: 'Route or Record Not found'
                  -
                    description: 'Bad Request'
                    type: object
                    example:
                      message: 'The POST method is not supported for route api/v1/customers/1/phones/16. Supported methods: GET, HEAD, PUT, PATCH'
                    properties:
                      message:
                        type: string
                        example: 'The POST method is not supported for route api/v1/customers/1/phones/16. Supported methods: GET, HEAD, PUT, PATCH'
        500:
          description: 'Internal Server Error'
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Internal Server Error'
                properties:
                  message:
                    type: string
                    example: 'Internal Server Error'
      tags:
        - Customers
    put:
      summary: 'Update Customer'
      operationId: updateCustomer
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    customer_id: 1
                    name: 'Dr. Michel Metz'
                    tax_number: 01JAC01XM90NABCXSMNJTQKW58
                    tax_rate: 17.5
                    created_at: '2024-10-17 01:04:12'
                    updated_at: '2024-10-17 01:04:12'
                properties:
                  data:
                    type: object
                    properties:
                      customer_id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: 'Dr. Michel Metz'
                      tax_number:
                        type: string
                        example: 01JAC01XM90NABCXSMNJTQKW58
                      tax_rate:
                        type: number
                        example: 17.5
                      created_at:
                        type: string
                        example: '2024-10-17 01:04:12'
                      updated_at:
                        type: string
                        example: '2024-10-17 01:04:12'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthorized
                properties:
                  message:
                    type: string
                    example: Unauthorized
        404:
          description: ''
          content:
            application/json:
              schema:
                oneOf:
                  -
                    description: 'Not Found'
                    type: object
                    example:
                      message: 'Route or Record Not found'
                    properties:
                      message:
                        type: string
                        example: 'Route or Record Not found'
                  -
                    description: 'Bad Request'
                    type: object
                    example:
                      message: 'The POST method is not supported for route api/v1/customers/1/phones/16. Supported methods: GET, HEAD, PUT, PATCH'
                    properties:
                      message:
                        type: string
                        example: 'The POST method is not supported for route api/v1/customers/1/phones/16. Supported methods: GET, HEAD, PUT, PATCH'
        422:
          description: 'Validation Failed'
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Validation Failed'
                  fields:
                    type:
                      - 'The selected type is invalid.'
                    name:
                      - 'The name field must not be greater than 64 characters.'
                properties:
                  message:
                    type: string
                    example: 'Validation Failed'
                  fields:
                    type: object
                    properties:
                      type:
                        type: array
                        example:
                          - 'The selected type is invalid.'
                        items:
                          type: string
                      name:
                        type: array
                        example:
                          - 'The name field must not be greater than 64 characters.'
                        items:
                          type: string
        500:
          description: 'Internal Server Error'
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Internal Server Error'
                properties:
                  message:
                    type: string
                    example: 'Internal Server Error'
      tags:
        - Customers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must be at least 3 characters. Must not be greater than 64 characters.'
                  example: 'John Doe'
                tax_number:
                  type: string
                  description: 'Must be at least 3 characters. Must not be greater than 64 characters.'
                  example: ABCD-1234
                tax_rate:
                  type: number
                  description: 'Must be between 0 and 100.'
                  example: 12.5
              required:
                - name
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the customer.'
        example: 1
        required: true
        schema:
          type: integer
  '/api/v1/customers/{customer_id}/emails':
    get:
      summary: 'List Customer Emails'
      operationId: listCustomerEmails
      description: ''
      parameters:
        -
          in: query
          name: search
          description: 'Search for customer emails by name or address'
          example: john.doe@example.com
          required: false
          schema:
            type: string
            description: 'Search for customer emails by name or address'
            example: john.doe@example.com
        -
          in: query
          name: per_page
          description: 'Number of results per page (Min 25, Max 100)'
          example: 25
          required: false
          schema:
            type: integer
            description: 'Number of results per page (Min 25, Max 100)'
            example: 25
        -
          in: query
          name: page
          description: 'Page number'
          example: 1
          required: false
          schema:
            type: integer
            description: 'Page number'
            example: 1
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      customer_email_id: 1
                      name: "Cortney D'Amore"
                      address: junius79@example.com
                      is_default: true
                      created_at: '2024-10-17 01:04:12'
                      updated_at: '2024-10-17 01:04:12'
                    -
                      customer_email_id: 1
                      name: 'Alycia Emmerich'
                      address: ansel.jenkins@example.org
                      is_default: true
                      created_at: '2024-10-17 01:04:12'
                      updated_at: '2024-10-17 01:04:12'
                  links:
                    first: '/?page=1'
                    last: null
                    prev: null
                    next: null
                  meta:
                    current_page: 1
                    from: 1
                    path: /
                    per_page: 25
                    to: 2
                properties:
                  data:
                    type: array
                    example:
                      -
                        customer_email_id: 1
                        name: "Cortney D'Amore"
                        address: junius79@example.com
                        is_default: true
                        created_at: '2024-10-17 01:04:12'
                        updated_at: '2024-10-17 01:04:12'
                      -
                        customer_email_id: 1
                        name: 'Alycia Emmerich'
                        address: ansel.jenkins@example.org
                        is_default: true
                        created_at: '2024-10-17 01:04:12'
                        updated_at: '2024-10-17 01:04:12'
                    items:
                      type: object
                      properties:
                        customer_email_id:
                          type: integer
                          example: 1
                        name:
                          type: string
                          example: "Cortney D'Amore"
                        address:
                          type: string
                          example: junius79@example.com
                        is_default:
                          type: boolean
                          example: true
                        created_at:
                          type: string
                          example: '2024-10-17 01:04:12'
                        updated_at:
                          type: string
                          example: '2024-10-17 01:04:12'
                  links:
                    type: object
                    properties:
                      first:
                        type: string
                        example: '/?page=1'
                      last:
                        type: string
                        example: null
                      prev:
                        type: string
                        example: null
                      next:
                        type: string
                        example: null
                  meta:
                    type: object
                    properties:
                      current_page:
                        type: integer
                        example: 1
                      from:
                        type: integer
                        example: 1
                      path:
                        type: string
                        example: /
                      per_page:
                        type: integer
                        example: 25
                      to:
                        type: integer
                        example: 2
      tags:
        - 'Customer Emails'
    post:
      summary: 'Create Customer Email'
      operationId: createCustomerEmail
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    customer_email_id: 1
                    name: 'Sincere Brekke'
                    address: cayla95@example.net
                    is_default: true
                    created_at: '2024-10-17 01:04:12'
                    updated_at: '2024-10-17 01:04:12'
                properties:
                  data:
                    type: object
                    properties:
                      customer_email_id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: 'Sincere Brekke'
                      address:
                        type: string
                        example: cayla95@example.net
                      is_default:
                        type: boolean
                        example: true
                      created_at:
                        type: string
                        example: '2024-10-17 01:04:12'
                      updated_at:
                        type: string
                        example: '2024-10-17 01:04:12'
      tags:
        - 'Customer Emails'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must be at least 3 characters. Must not be greater than 64 characters.'
                  example: 'John Doe'
                address:
                  type: string
                  description: 'Must be a valid email address. Must be at least 3 characters. Must not be greater than 256 characters.'
                  example: john.doe@example.com
                is_default:
                  type: boolean
                  description: ''
                  example: false
              required:
                - name
                - address
    parameters:
      -
        in: path
        name: customer_id
        description: 'The ID of the customer.'
        example: 1
        required: true
        schema:
          type: integer
  '/api/v1/customers/{customer_id}/emails/{id}':
    get:
      summary: 'Get Customer Email'
      operationId: getCustomerEmail
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    customer_email_id: 1
                    name: 'Wilbert Johnson'
                    address: nikolaus.abbigail@example.com
                    is_default: true
                    created_at: '2024-10-17 01:04:12'
                    updated_at: '2024-10-17 01:04:12'
                properties:
                  data:
                    type: object
                    properties:
                      customer_email_id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: 'Wilbert Johnson'
                      address:
                        type: string
                        example: nikolaus.abbigail@example.com
                      is_default:
                        type: boolean
                        example: true
                      created_at:
                        type: string
                        example: '2024-10-17 01:04:12'
                      updated_at:
                        type: string
                        example: '2024-10-17 01:04:12'
      tags:
        - 'Customer Emails'
    put:
      summary: 'Update Customer Email'
      operationId: updateCustomerEmail
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    customer_email_id: 1
                    name: 'Prof. Wallace Ryan'
                    address: ppaucek@example.org
                    is_default: true
                    created_at: '2024-10-17 01:04:12'
                    updated_at: '2024-10-17 01:04:12'
                properties:
                  data:
                    type: object
                    properties:
                      customer_email_id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: 'Prof. Wallace Ryan'
                      address:
                        type: string
                        example: ppaucek@example.org
                      is_default:
                        type: boolean
                        example: true
                      created_at:
                        type: string
                        example: '2024-10-17 01:04:12'
                      updated_at:
                        type: string
                        example: '2024-10-17 01:04:12'
      tags:
        - 'Customer Emails'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must be at least 3 characters. Must not be greater than 64 characters.'
                  example: 'John Doe'
                address:
                  type: string
                  description: 'Must be a valid email address. Must be at least 3 characters. Must not be greater than 256 characters.'
                  example: john.doe@example.com
                is_default:
                  type: boolean
                  description: ''
                  example: false
              required:
                - name
                - address
    parameters:
      -
        in: path
        name: customer_id
        description: 'The ID of the customer.'
        example: 1
        required: true
        schema:
          type: integer
      -
        in: path
        name: id
        description: 'The ID of the email.'
        example: 1
        required: true
        schema:
          type: integer
  '/api/v1/customers/{customer_id}/phones':
    get:
      summary: 'List Customer Phones'
      operationId: listCustomerPhones
      description: ''
      parameters:
        -
          in: query
          name: type
          description: ''
          example: Mobile
          required: false
          schema:
            type: string
            description: ''
            example: Mobile
            enum:
              - Home
              - Office
              - Mobile
        -
          in: query
          name: search
          description: 'Search for customer phones by name or number'
          example: '0123456789'
          required: false
          schema:
            type: string
            description: 'Search for customer phones by name or number'
            example: '0123456789'
        -
          in: query
          name: per_page
          description: 'Number of results per page (Min 25, Max 100)'
          example: 25
          required: false
          schema:
            type: integer
            description: 'Number of results per page (Min 25, Max 100)'
            example: 25
        -
          in: query
          name: page
          description: 'Page number'
          example: 1
          required: false
          schema:
            type: integer
            description: 'Page number'
            example: 1
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      customer_phone_id: 1
                      type: Home
                      name: 'Electa Dickens'
                      number: '+16206269677'
                      is_default: true
                      created_at: '2024-10-17 01:04:12'
                      updated_at: '2024-10-17 01:04:12'
                    -
                      customer_phone_id: 1
                      type: Office
                      name: 'Xzavier Erdman'
                      number: 1-267-987-9082
                      is_default: true
                      created_at: '2024-10-17 01:04:12'
                      updated_at: '2024-10-17 01:04:12'
                  links:
                    first: '/?page=1'
                    last: null
                    prev: null
                    next: null
                  meta:
                    current_page: 1
                    from: 1
                    path: /
                    per_page: 25
                    to: 2
                properties:
                  data:
                    type: array
                    example:
                      -
                        customer_phone_id: 1
                        type: Home
                        name: 'Electa Dickens'
                        number: '+16206269677'
                        is_default: true
                        created_at: '2024-10-17 01:04:12'
                        updated_at: '2024-10-17 01:04:12'
                      -
                        customer_phone_id: 1
                        type: Office
                        name: 'Xzavier Erdman'
                        number: 1-267-987-9082
                        is_default: true
                        created_at: '2024-10-17 01:04:12'
                        updated_at: '2024-10-17 01:04:12'
                    items:
                      type: object
                      properties:
                        customer_phone_id:
                          type: integer
                          example: 1
                        type:
                          type: string
                          example: Home
                        name:
                          type: string
                          example: 'Electa Dickens'
                        number:
                          type: string
                          example: '+16206269677'
                        is_default:
                          type: boolean
                          example: true
                        created_at:
                          type: string
                          example: '2024-10-17 01:04:12'
                        updated_at:
                          type: string
                          example: '2024-10-17 01:04:12'
                  links:
                    type: object
                    properties:
                      first:
                        type: string
                        example: '/?page=1'
                      last:
                        type: string
                        example: null
                      prev:
                        type: string
                        example: null
                      next:
                        type: string
                        example: null
                  meta:
                    type: object
                    properties:
                      current_page:
                        type: integer
                        example: 1
                      from:
                        type: integer
                        example: 1
                      path:
                        type: string
                        example: /
                      per_page:
                        type: integer
                        example: 25
                      to:
                        type: integer
                        example: 2
      tags:
        - 'Customer Phones'
    post:
      summary: 'Create Customer Phone'
      operationId: createCustomerPhone
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    customer_phone_id: 1
                    type: Mobile
                    name: 'Prof. Corine Cartwright MD'
                    number: +1-402-338-2805
                    is_default: true
                    created_at: '2024-10-17 01:04:12'
                    updated_at: '2024-10-17 01:04:12'
                properties:
                  data:
                    type: object
                    properties:
                      customer_phone_id:
                        type: integer
                        example: 1
                      type:
                        type: string
                        example: Mobile
                      name:
                        type: string
                        example: 'Prof. Corine Cartwright MD'
                      number:
                        type: string
                        example: +1-402-338-2805
                      is_default:
                        type: boolean
                        example: true
                      created_at:
                        type: string
                        example: '2024-10-17 01:04:12'
                      updated_at:
                        type: string
                        example: '2024-10-17 01:04:12'
      tags:
        - 'Customer Phones'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  description: ''
                  example: Home
                  enum:
                    - Home
                    - Office
                    - Mobile
                name:
                  type: string
                  description: 'Must be at least 3 characters. Must not be greater than 64 characters.'
                  example: 'John Doe'
                number:
                  type: string
                  description: 'Must be at least 3 characters. Must not be greater than 32 characters.'
                  example: +1-956-745-2290
                is_default:
                  type: boolean
                  description: ''
                  example: false
              required:
                - type
                - name
                - number
    parameters:
      -
        in: path
        name: customer_id
        description: 'The ID of the customer.'
        example: 1
        required: true
        schema:
          type: integer
  '/api/v1/customers/{customer_id}/phones/{id}':
    get:
      summary: 'Get Customer Phone'
      operationId: getCustomerPhone
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    customer_phone_id: 1
                    type: Home
                    name: 'Miss Jazmyn Johnston DVM'
                    number: '+1 (765) 531-1129'
                    is_default: true
                    created_at: '2024-10-17 01:04:12'
                    updated_at: '2024-10-17 01:04:12'
                properties:
                  data:
                    type: object
                    properties:
                      customer_phone_id:
                        type: integer
                        example: 1
                      type:
                        type: string
                        example: Home
                      name:
                        type: string
                        example: 'Miss Jazmyn Johnston DVM'
                      number:
                        type: string
                        example: '+1 (765) 531-1129'
                      is_default:
                        type: boolean
                        example: true
                      created_at:
                        type: string
                        example: '2024-10-17 01:04:12'
                      updated_at:
                        type: string
                        example: '2024-10-17 01:04:12'
      tags:
        - 'Customer Phones'
    put:
      summary: 'Update Customer Phone'
      operationId: updateCustomerPhone
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    customer_phone_id: 1
                    type: Home
                    name: 'Dr. Mortimer Hoeger'
                    number: 1-220-741-8692
                    is_default: true
                    created_at: '2024-10-17 01:04:12'
                    updated_at: '2024-10-17 01:04:12'
                properties:
                  data:
                    type: object
                    properties:
                      customer_phone_id:
                        type: integer
                        example: 1
                      type:
                        type: string
                        example: Home
                      name:
                        type: string
                        example: 'Dr. Mortimer Hoeger'
                      number:
                        type: string
                        example: 1-220-741-8692
                      is_default:
                        type: boolean
                        example: true
                      created_at:
                        type: string
                        example: '2024-10-17 01:04:12'
                      updated_at:
                        type: string
                        example: '2024-10-17 01:04:12'
      tags:
        - 'Customer Phones'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  description: ''
                  example: Office
                  enum:
                    - Home
                    - Office
                    - Mobile
                name:
                  type: string
                  description: 'Must be at least 3 characters. Must not be greater than 64 characters.'
                  example: 'John Doe'
                number:
                  type: string
                  description: 'Must be at least 3 characters. Must not be greater than 32 characters.'
                  example: +1-956-745-2290
                is_default:
                  type: boolean
                  description: ''
                  example: false
              required:
                - type
                - name
                - number
    parameters:
      -
        in: path
        name: customer_id
        description: 'The ID of the customer.'
        example: 1
        required: true
        schema:
          type: integer
      -
        in: path
        name: id
        description: 'The ID of the phone.'
        example: 1
        required: true
        schema:
          type: integer
tags:
  -
    name: Customers
    description: 'Customer Management API'
  -
    name: 'Customer Emails'
    description: 'Customer Email Management API'
  -
    name: 'Customer Phones'
    description: 'Customer Phone Management API'
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: 'You can generate your token by logging in and clicking your name, and then <a href="/user/api-tokens"><b>API Tokens</b></a>.'
security:
  -
    default: []
